/**
 * Auth Keys.
 */
export const AUTH_KEYS = {
	RESET_PASSWORD_SESSION_KEY: 'RESET_PASSWORD_SESSION_KEY',
}

/**
 * Stripe Keys.
 */
export const STRIPE_KEYS = {
	HAS_SUCCESSFULLY_SUBSCRIBED: 'HAS_SUCCESSFULLY_SUBSCRIBED',
	HAS_UNSUCCESSFULLY_SUBSCRIBED: 'HAS_UNSUCCESSFULLY_SUBSCRIBED',
	HAS_SUCCESSFULLY_UPDATED_PLAN: 'HAS_SUCCESSFULLY_UPDATED_PLAN',
}

/**
 * Email Keys.
 */
export const EMAIL_KEYS = {
	HAS_SUCCESSFULLY_SEND_EMAIL: 'HAS_SUCCESSFULLY_SEND_EMAIL',
}

/**
 * Misc Keys.
 */
export const MISC_KEYS = {
	QUERY_TOKEN_PARAM: 'token',
	QUERY_TOKEN_FORGOT_PASSWORD: 'forgot-password',
}
