/**
 * Action Intents.
 */
export const INTENTS = {
  INTENT: 'INTENT',
  USER_UPDATE_USERNAME: 'USER_UPDATE_USERNAME',
  USER_DELETE_ACCOUNT: 'USER_DELETE_ACCOUNT',
  USER_DELETE: 'USER_DELETE',
  SUBSCRIPTION_CREATE_CHECKOUT: 'SUBSCRIPTION_CREATE_CHECKOUT',
  SUBSCRIPTION_CREATE_CUSTOMER_PORTAL: 'SUBSCRIPTION_CREATE_CUSTOMER_PORTAL',
} as const
