/**
 * Constants.
 */
const HAS_SUCCESSFULLY_SUBSCRIBED = 'HAS_SUCCESSFULLY_SUBSCRIBED'
const HAS_SUCCESSFULLY_UPDATED_PLAN = 'HAS_SUCCESSFULLY_UPDATED_PLAN'
const HAS_SKIPPED_SUBSCRIPTION_CHECK = 'HAS_SKIPPED_SUBSCRIPTION_CHECK'

export {
	HAS_SUCCESSFULLY_SUBSCRIBED,
	HAS_SUCCESSFULLY_UPDATED_PLAN,
	HAS_SKIPPED_SUBSCRIPTION_CHECK,
}
